version: '3'

tasks:
    setup-dev:
        desc: 'Setup workspace'
        cmds:
            - 'uv sync --frozen --all-extras'
            - 'lefthook install'
            - 'bun --cwd=playground install'
            - 'uv build --out-dir=playground/public'
    playground:
        desc: 'Start playground on localhost'
        cmds:
            - 'bun --cwd=playground dev'
    release-*:
        desc: 'Run release process'
        vars:
            LEVEL: '{{index .MATCH 0}}'
        cmds:
            - 'age {{.LEVEL}}'
            - 'uv sync --all-extras' # To write out as lock-file
